spring:
  application:
    name: ShoppingGql
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: toor
  devtools:
    restart:
      additional-exclude: logs/**
  graphql:
    graphiql:
      enabled: true
    path: /graphql
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
server:
  http2:
    enabled: true

graphql:
  playground:
    enabled: true
    page-title: Playground
    endpoint: /graphql
